### PR TITLE
[frontend] control enabled, more items, get username

### LINKED ISSUE #151: New product is disabled and can't be enable
**Describe the bug**
As title
The issue seems come from the misuse `enabled` with `enable`
the current `POST` request's content for creating product looks like
```form
name: flower
description: always please
image: (binary)
price: 20
expire_date: 2024-01-30T00:00:00.000Z
stock: 100
enable: true
tags: 19
```
**To Reproduce**
- Create any product as seller
- view corresponding shop's product as customer, can't find the product just create
- seller can't change the status of product too

**Expected behavior**
- There need a checkbox or button let seller to enable or disable the product
- The default value for `"enabled"` should be `true` when creating a new product

### PR DESCRIPTION
**Pull request by KatoToyoki**
Resolveeeeeeeees part of #94

### Changes

- add more item in manageProducts, UserViewShop, discover, buyer&seller history page
- add tag to corresponding user rather than putting `user1`
- seller can control if product is visible or not
  - image
  - image

### Test Environment Setup
open 3 terminals
one for `docker-compose up postgres minio `
one for `go run .`
one for `cd frontend` -> `npm i` -> `npm run build`
then open the browser then enter http://localhost:8080/ 

### Additional context

N/A

### CODE REVIEW

**Review by NOOBDY — APPROVED** [review]

**Review by Error0229 — APPROVED** [review]
womm

File: frontend/src/pages/user/seller/allProducts/index.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ const Products = () => {
   const { status, data: sellerShopData } = useQuery({
     queryKey: ['sellerShopView'],
     queryFn: async () => {
-      const response = await fetch(`/api/seller/product?offset=${0}&limit=${8}`, {
+      const response = await fetch(`/api/seller/product?offset=${0}&limit=${20}`, {
```
Comment (UGisBusy) [inline frontend/src/pages/user/seller/allProducts/index.tsx:18]: is this intended? do u want to change this page showing 20 items?
i might have to change the value in [#146](https://github.com/jykuo-love-shiritori/twp/issues/146).
( u dont need to change here either way, since ill overwrite it in that pr i. Just let me know it's 8 or 20)

Comment (KatoToyoki) [reply frontend/src/pages/user/seller/allProducts/index.tsx:18]: you can reset to original, thanks
