### PR TITLE
[backend] more swagger

### LINKED ISSUE #121: ambiguous type and name & lacks of object on doc
**Describe the bug**
### ambiguous type and name
  - POST `/seller/coupon/{id}/tag`
  - POST `/seller/product/{id}/tag`
  1. the name `id` can be more specific, and its type perhaps should be `number`
  2. the name `tag_id` seems like an individual id but it actually is an object, and `name:string` will not work

### lacks of object
- GET `/seller/product/{id}` lacks of `expire_date`

**To Reproduce**
open [Swagger](http://localhost:8080/swagger///index.html)
go to 
1. [POST /seller/coupon/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_coupon__id__tag)
2. [POST /seller/product/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_product__id__tag)
3. [GET /seller/product/{id}](http://localhost:8080/swagger///index.html#/Shop/get_seller_product__id_)

**Screenshots**
### ambiguous type and name
  image
  image

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by x06lan**
Ex. Resolves #121

### Changes
* fix swagger parameter type
* GET /seller/product/{id} return expire_date

### Testing Approach (if unconventional)

1. [POST /seller/coupon/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_coupon__id__tag)
2. [POST /seller/product/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_product__id__tag)
3. [GET /seller/product/{id}](http://localhost:8080/swagger///index.html#/Shop/get_seller_product__id_)

### CODE REVIEW

**Review by KatoToyoki — DISMISSED** [review]

File: pkg/router/seller/product.go [hunk 1]
```diff
@@ -96,13 +96,13 @@ func ListProduct(pg *db.DB, mc *minio.MC, logger *zap.SugaredLogger) echo.Handle
...
+// @Param			name		formData	string	true	"name of product"			default(A)
+// @Param			description	formData	string	true	"description of product"	default("description")
+// @Param			price		formData	number	true	"price"						default(19.99)
 // @Param			image		formData	file	true	"image id"
-// @Param			expire_date	formData	string	true	"expire date"
-// @Param			stock		formData	int		true	"stock"
-// @Param			enabled		formData	string	true	"enabled"
+// @Param			expire_date	formData	string	true	"expire date"	default(2024-10-12T07:20:50.52Z)
+// @Param			stock		formData	int		true	"stock"			default(10)
+// @Param			enabled		formData	string	true	"enabled"		default(true)
```
Comment (NOOBDY) [inline pkg/router/seller/product.go]:
```suggestion
// @Param			enabled		formData	bool	true	"enabled"		default(true)
```

**Review by NOOBDY — CHANGES_REQUESTED** [review]

**Review by NOOBDY — APPROVED** [review]

**Review by KatoToyoki — APPROVED** [review]
