### PR TITLE
[backend] Fix #137

### LINKED ISSUE #137: Product info API can't get corresponding shop's `seller_name`
**Describe the bug**
As title

**To Reproduce**
Call `/api/product/:id`
the response don't have  `seller_name`, `shop_name`, `shop_image_url` in response

**Expected behavior**
have  `seller_name`, `shop_name`, `shop_image_url` in response

### PR DESCRIPTION
**Pull request by Error0229**
Resolves #137
the current response for  `/api/product/:id` is 
```json
{
  "description": "string",
  "expire_date": "string",
  "id": 0,
  "name": "string",
  "price": 0,
  "product_image_url": "string",
  "sales": 0,
  "seller_name": "string",
  "shop_image_url": "string",
  "shop_name": "string",
  "stock": 0
}
```
### Changes
- Add `seller_name`, `shop_name`, `shop_image_url` for `/api/product/:id`

### Testing Approach (if unconventional)

Call `/api/product/:id` with any exist and enable product's id
It should include corresponding shop's  `seller_name`, `shop_name`, `shop_image_url` in response.

### CODE REVIEW

File: db/queries/general.sql [hunk 1]
```diff
@@ -49,19 +49,21 @@ WHERE
...
-    "sales"
+    P."id",
+    P."name",
+    P."description",
+    P."price",
+    P."image_id" AS "image_url",
+    P."expire_date",
+    P."stock",
+    P."sales",
+    S."seller_name" AS "seller_name"
```
Comment (x06lan) [inline db/queries/general.sql:62]: shop image and shop name

**Review by NOOBDY — DISMISSED** [review]

**Review by kryr34 — DISMISSED** [review]

**Review by kryr34 — APPROVED** [review]
LGTM

**Review by x06lan — APPROVED** [review]
